### ISSUE TITLE
Debugging cartpole.blend.py in VScode

### ISSUE THREAD

**Issue by TaeilJin** [cheind/pytorch-blender#10]
Hi

I have a question about debugging issue I met with cartpole example.

I use docker, and IDE is a VScode.

I try to debug the function inside a "cartpole.blend.py", but breakpoints are not working.

What I've figured out so far is that "cartpole.blend.py" is executed as command by subprocess.Popen(cmd,..).

I am a beginner, so It will be a silly question though.

Is there any way to debug the remote code which executed by command? 
Could you tell me which is your IDE for this project?

**Comment by cheind** [comment]
Hey and sorry for the late reply!

The content of `cartpole.blend.py` will indeed be run in a separate Blender process. So the question to ask would probably be: how can I debug a subprocess in Python. Unfortunately, I have no definite answer for that. But maybe this will help

https://stackoverflow.com/questions/4716533/how-to-attach-debugger-to-a-python-subproccess

In case you have some insights, let us know. I'm pretty sure other are struggling from the same issue.
