### ISSUE TITLE
datagen other complex scenes (than cubes)

### ISSUE THREAD

**Issue by ggaziv** [cheind/pytorch-blender#11]
Hi, thanks for this amazing package !
I was wondering how to go about making diverse scenes other than cubes. Is there anywhere I could download these?
Specially, say I download some .blend files off the internet, how to make suitable .py files for their integration?
Also, how does background diversification come into play?

Thanks !
Guy

**Comment by cheind** [comment]
Hey,

our latest paper https://arxiv.org/abs/2010.11696 considers object detection as an example. Here the TLESS dataset provides the CAD files of objects, the scene is a simple planar surface. We randomize objects above the plane and let physics create constellation of fallen objects. The code can be found here https://github.com/cheind/pytorch-blender-dr/tree/master/blender/tless but is not necessarily very clean at this point.
