### ISSUE TITLE
Code for generating object detection dataset

### ISSUE THREAD

**Issue by bamps53** [cheind/pytorch-blender#12]
Hi, thanks for sharing the interesting work!
do you have a plan to release the code for generating object detection dataset?
(which is described in IV. EXPERIMENTS B in https://arxiv.org/pdf/2010.11696.pdf)

**Comment by cheind** [comment]
Hey!

The code is already made public

https://github.com/cheind/pytorch-blender-dr

However, the code ist not in a very clean state. We wanted to fix this before reintegrating it into pytorch-blender, but haven't found the time yet. In particular, the relevant branches are

https://github.com/cheind/pytorch-blender-dr/tree/blexp/blender/tless

and a good model was also 

https://github.com/cheind/pytorch-blender-dr/blob/camera_noise/blender/tless/

which refer to pytorch-blender branch

https://github.com/cheind/pytorch-blender/tree/feature/compositor_support

for compositor support (camera noise postprocessing).

I will get in touch with Lukas for his comments.

**Comment by bamps53** [comment]
Wow, I didn't realize it! That's awesome.
Thank you so much for detailed answer and support.
I'll look through it:)

**Comment by cheind** [comment]
No worries, it was not meant to be found at this stage :)

**Comment by bamps53** [comment]
That's why I thanks more, you could just say "we'll release soon", but you didn't ;)

**Comment by lukasbrunnerjku** [comment]
Hi, I can clean it next weekend so you can have it as soon as possible :)

**Comment by cheind** [comment]
@bamps53, @lukasbrunnerjku just merged compositor-support alongside with some other fixes to develop. please let me know if that causes troubles for tless.

**Comment by bamps53** [comment]
Thank you so much!
I'll try it out:)
Thanks again for your generous support.

**Comment by cheind** [comment]
Hey @bamps53, lukas just merged a cleaned up version to master:

https://github.com/cheind/pytorch-blender-dr

Hope you find it useful
