### ISSUE TITLE
the support for a virtual camera binding on a moving agent

### ISSUE THREAD

**Issue by NowLoadY** [cheind/pytorch-blender#29]
GOD! I explored "examples/control," and it's fantastic. However, I have a further inquiry: Can I(or is it possible) add a camera to the agent, enabling it to observe the environment?

**Comment by cheind** [comment]
Hey @NowLoadY - not exactly sure what you are asking for. Blendtorch supports offline rendering to images via ` btb.OffScreenRenderer` that you pass a Blender camera name. When this camera is constrained/bound to other actors, then so are the generated images. You might need to tweak the example:

https://github.com/cheind/pytorch-blender/blob/develop/examples/control/cartpole_gym/envs/cartpole.blend.py#L31

to inclued the rendered image in the dict returned.

Hope this helps?

**Comment by NowLoadY** [comment]
hello @cheind :
I appreciate your clarification. I understand now that 'btb.OffScreenRenderer' can be utilized as a camera that is bound to the agent with constraints on movement and rotation. I will modify the code at the location you've pointed out to ensure that the rendered images are passed through a dictionary into the model's training process. Your guidance is very helpful. 
(translated to english, so i'm not sure wether am i write polite, but totally appreciate :) )
