### ISSUE TITLE
Enhancment for background support

### ISSUE THREAD

**Issue by GNovich** [cheind/pytorch-blender#9]
"Despite offscreen rendering is supported in Blender 2.8x it requires a UI frontend and thus cannot run in --background mode."

Until official support by blender, this could be worked-around for EEVEE by configuring a fake monitor. 
This is what I used for my head-less linux setup [See answer here](https://blender.stackexchange.com/questions/144083/how-to-get-blender-2-80-to-render-through-an-ssh-connection-minimal-working-ex/176110#176110).

**Comment by cheind** [comment]
Thanks, added a link to the main readme.
